import { GetServerSideProps } from "next";
import Head from "next/head";
import { Character } from "../../utils/types";

const CharacterDetail = ({ person }: { person: Character }) => {

const { id, name, gender, image, species, status, location } = person;

return (
  <div className="container">
    <Head>
      <title>{name} </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="main">
      <div>
        <article className="character-detail-article">
          <picture>
            <source media="(max-width: 425px)" srcSet={image} />
            <img loading="lazy" src={image} alt={name} title={name} />
          </picture>
          <div className="character-description">
            <h1 className="title">{name}</h1>
            <ul className="character-description-items">
              <li>
                <p>
                  <strong>Id:</strong> {id}
                </p>
              </li>
              <li>
                <p>
                  <strong>Gender:</strong> {gender}
                </p>
              </li>
              <li>
                <p>
                  <strong>Specie:</strong> {species}
                </p>
              </li>
              <li>
                <p>
                  <strong>Status:</strong>
                  {status}
                </p>
              </li>
              <li>
                <p>
                  <strong> Location:</strong> {location?.name}
                </p>
              </li>
            </ul>
          </div>
        </article>
      </div>
    </main>
  </div>
 );
};
export default CharacterDetail;

export const getServerSideProps: GetServerSideProps = async (context)  => {
 
    console.log({context});
    const { character } = context.query;
    const response = await fetch(
      `https://rickandmortyapi.com/api/character/${character}`
    );
    const person = await response.json();
    return {
      props: {
        person,
        error: false,
      },
    };
};
    
