import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../utils/types'
interface HomeProps {
  characters: GetCharacterResults;
}

const Home: NextPage <HomeProps> = ({ characters }) => {
  const { results } = characters;
  console.log(characters);
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
       <h1 className="title">Rick & Morty Characters</h1>
       <section>
         <ul className="characters-list">
           {results && results.map((item, index) => (
             console.log(item),
             <Card character={item} key={index}/> 
           ))}
         </ul>
       </section>
     </main>

     </div>
  )
}

export default Home

export const getServerSideProps: GetStaticProps = async () => {
  const apiLink = 'https://rickandmortyapi.com/api/character/?page=1';
  const response = await fetch(apiLink);
  const characters = await response.json();

  return {
    props: {
      characters,
    }
  }
 }

 